### ISSUE TITLE
Editor keeps being focussed beside disabled in options

### ISSUE THREAD

**Issue by mechanoid** [olmokramer/atom-single-click-open#2]
Since the newest atom update (1.10.2), it seems, that your plugin is broken for that settings option. 
Whether "Focus Editor On Open" is checked or not, does not change the behaviour of the editor.

**Comment by MiracleBlue** [comment]
Interesting.  It is entirely possible that Atom has made focus on open the default behaviour in general.  What would your preferred behaviour be when this checkbox is disabled?  Let me know and I'll have a think about whether it's something we can explicitly add to the plugin :)

**Comment by mechanoid** [comment]
At the moment it seems impossible to have the file entry in the tree to be focussed after a click. A common task for me is to click on an entry in tree view followed by `m` or `backspace` to rename/relocate it, or to just delete it. What i am ending up with are a lot of m-characters in the focussed files instead :) 
So yes i guess that "focus editor" is now the default which drives me insane :D

**Comment by mechanoid** [comment]
Hmm, just updated the single-click open version and it seems to work now ... 🤕 I'll guess we should close this issue. If it appears again i will open a new one and hopefully with an PR attached :) Thanks anyway!
